### PR TITLE
Adopt wil::unique_* RAII for Win32 handles + BSTR/CoTaskMem

### LINKED ISSUE #37: Adopt wil/resource.h (wil::unique_*) for Win32 handles across the codebase
## Goal
Adopt **`wil/resource.h` RAII wrappers** for raw Win32 handles across the codebase, replacing manual `CloseHandle`/`FreeLibrary`/`DeleteObject`/`RegCloseKey`/etc. This complements the COM-pointer cleanup (#10) — same "use WIL RAII" theme, handles instead of interfaces.

Do it as **one PR** once #23 (WinForms) and #24 (COM ptrs) have landed (so it also covers `src/tap_winforms/winforms_tap_native.cpp` and doesn't collide with #24's TAP edits).

## Scope (audit: ~160 sites across ~14 files)
Map raw handles to the appropriate `wil::unique_*`:
- Generic `HANDLE` (named pipes, events, files, `CreateToolhelp32Snapshot`) → `wil::unique_handle` / `wil::unique_hfile` / `wil::unique_event`
- Process/thread handles (`OpenProcess`, `CreateProcess` PROCESS_INFORMATION) → `wil::unique_process_handle` / `wil::unique_handle`
- `HMODULE` from `LoadLibrary` → `wil::unique_hmodule`
- Registry `HKEY` → `wil::unique_hkey`
- GDI objects in `screenshot.cpp` (`HDC`/`HBITMAP`/`HFONT`/`HPEN`/`HBRUSH`) → `wil::unique_hdc` / `wil::unique_hbitmap` / `wil::unique_hgdiobj`

### Files (raw-handle site counts)
- `src/plugin_avalonia/lvt_avalonia_plugin.cpp` (~22), `avalonia_tap_native.cpp` (~7)
- `src/providers/wpf_inject.cpp` (~21), `xaml_diag_common.cpp` (~21), `winui3_provider.cpp` (~4), `comctl_provider.cpp` (~2)
- `src/plugin_chromium/chromium_host.cpp` (~20), `lvt_chromium_plugin.cpp` (~19)
- `src/tap_wpf/wpf_tap_native.cpp` (~12), `src/tap/lvt_tap.cpp` (~5), `src/tap_winforms/winforms_tap_native.cpp` (after #23)
- `src/plugin_loader.cpp` (~4), `src/target.cpp` (~2), `src/framework_detector.cpp` (~1)
- `src/screenshot.cpp` (GDI objects)

## Caveats
- **TAP DLLs** (`lvt_tap`, `wpf_tap_native`, `winforms_tap_native`, `avalonia_tap_native`) use **static CRT (/MT) and avoid C++ exceptions** — use the **non-throwing** WIL forms there; do not introduce throwing helpers.
- Watch for handles whose ownership is **intentionally transferred** (e.g. a named-pipe handle handed to a fire-and-forget worker thread, or handles closed on another thread) — don't wrap in a way that double-closes or closes early.
- Behavior must be identical; this is a leak-hygiene/RAII refactor, not a functional change. Keep `build\lvt_unit_tests.exe` + integration tests green.

Relates to #10.

### PR DESCRIPTION
**Pull request by asklar**
Fixes #37

## Summary
- Replaced manual Win32 cleanup with `wil::unique_*` RAII across core providers, plugin loader, plugins, TAP DLLs, screenshot GDI, and integration fixtures.
- Converted BSTR/CoTaskMem cleanup in `src\tap\lvt_tap.cpp` to `wil::unique_bstr` and `wil::unique_cotaskmem`.
- Added WIL linkage for `lvt_avalonia_plugin`, `lvt_avalonia_tap`, `lvt_chromium_plugin`, and `lvt_chromium_host`.

## Converted sites
- Added wrappers: `unique_handle` 28, `unique_event` 16, `unique_hfile` 12, `unique_hmodule` 8, `unique_hlocal` 6, `unique_hfind` 4, `unique_bstr` 8, `unique_cotaskmem` 2, plus `unique_hdc`/GDI wrappers, `unique_hkey`, and `unique_hwnd`.
- Removed 139 manual cleanup calls (`CloseHandle`, `FreeLibrary`, `DeleteObject`, `DeleteDC`, `RegCloseKey`, `FindClose`, `SysFreeString`, `CoTaskMemFree`, `LocalFree`, `DestroyWindow`).

## Deliberately left raw
- `tests\integration_tests.cpp` window-proc `DestroyWindow(hwnd)`: the HWND is destroyed on its owning UI thread in response to a close message, not a scope-owned resource.
- TAP `FreeLibraryAndExitThread` calls remain raw by design because they atomically unload the injected DLL and exit the worker thread.
- `GetStdHandle` and `GetModuleHandle*` results remain raw/non-owning borrowed handles.

## Validation
- `cmake --preset default` passed.
- `dotnet build src\tap_wpf\LvtWpfTap.csproj -c Release` passed.
- `dotnet build src\plugin_avalonia\LvtAvaloniaTreeWalker\LvtAvaloniaTreeWalker.csproj -c Release` passed.
- `dotnet build src\tap_winforms\LvtWinFormsTap.csproj -c Release` passed.
- `cmake --build build` passed (existing Avalonia package vulnerability warnings; WinUI3 projection macro warning).
- `build\lvt_unit_tests.exe`: 60/60 passed.
- `build\lvt_chromium_tests.exe`: 18/18 passed.
- `build\lvt_integration_tests.exe`: 31 passed, 1 skipped (`NotepadFixture.XamlBoundsIfDetected`, XAML/UWP not detected for this Notepad instance).
- Targeted rerun after test-fixture HWND cleanup: `KnownWindowFixture.*:ComCtlWindowFixture.*` 5/5 passed.
- Smokes: Notepad `--frameworks` returned `win32` + `winui3 2.2.0.0`; screenshot smoke wrote a 47,748-byte PNG and was cleaned up; WinUI3 sample XML smoke wrote 36,560 bytes.

### CODE REVIEW

**Comment by asklar** [comment]
## Review follow-up: kept hostfxr resident in the TAP CLR hosts (pushed f786a64)

Reviewed the full diff (screenshot GDI, all pipe/event handles, process-injection, plugin loader, tap natives). The handle mapping is correct throughout — notably `unique_hfile` (INVALID_HANDLE_VALUE sentinel) for pipes/files vs `unique_event`/`unique_handle` (nullptr sentinel) for events/threads/processes, `unique_hlocal` for the security descriptors, and `remoteMem` correctly left as manual `VirtualFreeEx`. GDI de-selects originals before RAII deletes, and the alpha fix is preserved.

**One behavior change fixed** (commit f786a64): the three `TryNetCore` CLR-hosting paths (WPF/WinForms/Avalonia) had wrapped the **hostfxr.dll** fallback load in a scope-owned `wil::unique_hmodule`. The original loaded hostfxr as a raw HMODULE and **intentionally left it resident** for the process lifetime — it pins the hosted CoreCLR resolver in a *foreign, injected* process. Scope-freeing it on `TryNetCore` return could unload a host library out from under the still-running runtime. (In the common case hostfxr is already loaded → the wrapper was empty, so this only affected the load-fallback path — but it's a real divergence for a "no behavior change" PR.) Restored the exact original behavior + added an explanatory comment so it isn't "re-cleaned" later. `mscoree` in the .NET Framework path is unaffected (shim over the app's own CLR; original already freed it).

Validation after the fix: `cmake --build build` green, `lvt_unit_tests.exe` 60/60.

**Comment by asklar** [comment]
## cdb validation of the full handle refactor (139 sites) — clean

Ran lvt.exe under **cdb** (which raises `0xC0000008 STATUS_INVALID_HANDLE` on any double-close/invalid-handle, and `0xC0000005` on use-after-free) across all three managed-framework samples, with injection-stress (3 injections each) + break-on-invalid-handle (`sxe ch`) + break-on-AV (`sxe av`):

| Framework | Injections | Access violations | Invalid-handle (0xC0000008) | Target survived | Enriched |
|-----------|-----------|-------------------|------------------------------|-----------------|----------|
| WPF (net10) | 3 | 0 | 0 | ✅ | ✅ |
| WinForms | 3 | 0 | 0 | ✅ | ✅ |
| Avalonia | 3 | 0 | 0 | ✅ | ✅ |
| WPF screenshot (GDI path) | 1 | 0 | 0 | ✅ | valid PNG |

This exercises both sides of the refactor: lvt.exe's inject/pipe/screenshot/plugin-loader handle code **and** the injected TAP DLLs' handle code (a target-side double-close would crash the target — none did). Enrichment succeeding proves the handle code ran the full inject→pipe→read→graft path, not just early-outs.

Combined with: build green, 60/60 unit, CI green, and the hostfxr fix being a proven revert to `main`'s long-shipped behavior.

**Caveat (unchanged):** the rare hostfxr load-fallback branch still isn't force-exercised (a running .NET app has hostfxr resident), but everything around it is now debugger-verified and the fix itself is behavior-identical to shipped `main`.

**Comment by asklar** [comment]
Rebased onto `main` (past #40, which restructured `CMakeLists.txt` into `lvt_core`). The only textual conflict was an `#include` collision in `src/plugin_loader.cpp` (`<set>` vs `<utility>` — both kept). All four CMake hunks re-applied cleanly at their new positions, and none duplicates the `target_link_libraries(lvt_core PRIVATE ...)` that `main` already has.

### Three issues found and fixed while rebasing

**1. Public header depended on a PRIVATE dependency — broke the library story from #40.**
This branch changes `src/plugin_loader.h` to include `<wil/resource.h>` and expose `wil::unique_hmodule` in `struct LoadedPlugin`. That header is in `LVT_PUBLIC_HEADERS` (installed to `include/lvt/`), but `lvt_core` linked `WIL::WIL` as **PRIVATE**, so WIL include directories never reached consumers of `lvt::core`:

```
src/plugin_loader.h(7): fatal error C1083: Cannot open include file: 'wil/resource.h'
```

Fixed by promoting `WIL::WIL` to `PUBLIC`. No package plumbing needed — `cmake/lvtConfig.cmake.in` already does `find_dependency(wil CONFIG)` and `ports/lvt/vcpkg.json` already depends on `wil`.

**2. Added `lvt_public_headers_test` to stop that class of regression.**
A compile-only target that links `lvt_core` and adds *no* include directories of its own, so it sees exactly what an external consumer sees. Verified it genuinely catches the bug: reverting `WIL::WIL` to `PRIVATE` reproduces the C1083 above, and restoring `PUBLIC` makes it compile.

**3. `CoUninitialize` leak in `screenshot.cpp` — in scope for this PR, still present.**
`save_pixels_as_png` computed `bool needUninit` but only called `CoUninitialize()` on the success path, leaking the apartment on all **13** intervening `if (FAILED(hr)) return false;` paths. Replaced with `wil::unique_couninitialize_call`, `release()`d when `CoInitializeEx` fails so the previous semantics are preserved exactly.

### Re-validation (matrix re-run against the rebased tree)

| Check | Result |
|---|---|
| `cmake --preset default` + `cmake --build build` | clean |
| `lvt_unit_tests` | **60/60 passed** |
| `lvt_chromium_tests` | **18/18 passed** |
| `lvt_integration_tests` | **31 passed, 1 skipped** (`NotepadFixture.XamlBoundsIfDetected`) |
| Notepad `--frameworks` | `win32`, `winui3 2.3.0.0` |
| Screenshot smoke | 45,064-byte PNG |
| WinUI3 sample `--format xml` | 36,597 bytes, XAML subtree correctly grafted into `DesktopChildSiteBridge` |
